/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/carts": {
    /**
     * カート取得
     * @description ユーザーのカート情報を取得
     */
    get: operations["getCart"];
    /**
     * カートをクリア
     * @description カート内のすべてのアイテムを削除
     */
    delete: operations["clearCart"];
  };
  "/carts/items": {
    /**
     * アイテム追加
     * @description カートにアイテムを追加
     */
    post: operations["addItem"];
  };
  "/carts/items/{product_id}": {
    /**
     * アイテム更新
     * @description カート内のアイテム数量を更新
     */
    put: operations["updateItem"];
    /**
     * アイテム削除
     * @description カートからアイテムを削除
     */
    delete: operations["removeItem"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CartItem: {
      product_id?: string;
      product_name?: string;
      /** @description SKU ID (optional) */
      sku_id?: string;
      /** @description SKU code (optional) */
      sku_code?: string;
      /** @description SKU attributes like color, size (optional) */
      sku_attributes?: {
        [key: string]: string;
      };
      /** Format: double */
      price?: number;
      quantity?: number;
      /** Format: double */
      subtotal?: number;
      /** Format: date-time */
      added_at?: string;
    };
    Cart: {
      user_id?: string;
      items?: components["schemas"]["CartItem"][];
      /** Format: double */
      total?: number;
      item_count?: number;
      /** Format: date-time */
      last_modified?: string;
      /** Format: date-time */
      expires_at?: string;
    };
    AddItemRequest: {
      product_id: string;
      product_name: string;
      /** @description SKU ID (optional) */
      sku_id?: string;
      /** @description SKU code (optional) */
      sku_code?: string;
      /** @description SKU attributes like color, size (optional) */
      sku_attributes?: {
        [key: string]: string;
      };
      /** Format: double */
      price: number;
      quantity: number;
    };
    UpdateItemRequest: {
      quantity: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * カート取得
   * @description ユーザーのカート情報を取得
   */
  getCart: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Cart"];
        };
      };
      /** @description サーバーエラー */
      500: {
        content: never;
      };
    };
  };
  /**
   * カートをクリア
   * @description カート内のすべてのアイテムを削除
   */
  clearCart: {
    responses: {
      /** @description 成功 */
      204: {
        content: never;
      };
      /** @description リクエスト不正 */
      400: {
        content: never;
      };
    };
  };
  /**
   * アイテム追加
   * @description カートにアイテムを追加
   */
  addItem: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddItemRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Cart"];
        };
      };
      /** @description リクエスト不正 */
      400: {
        content: never;
      };
    };
  };
  /**
   * アイテム更新
   * @description カート内のアイテム数量を更新
   */
  updateItem: {
    parameters: {
      path: {
        product_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateItemRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Cart"];
        };
      };
      /** @description リクエスト不正 */
      400: {
        content: never;
      };
    };
  };
  /**
   * アイテム削除
   * @description カートからアイテムを削除
   */
  removeItem: {
    parameters: {
      path: {
        product_id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Cart"];
        };
      };
      /** @description リクエスト不正 */
      400: {
        content: never;
      };
    };
  };
}
