/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/orders": {
    /**
     * 注文履歴取得
     * @description ユーザーの注文履歴を取得
     */
    get: operations["getUserOrders"];
    /**
     * 注文作成
     * @description 新しい注文を作成
     */
    post: operations["createOrder"];
  };
  "/orders/{id}": {
    /**
     * 注文取得
     * @description 注文IDから注文情報を取得
     */
    get: operations["getOrder"];
  };
  "/orders/{id}/status": {
    /**
     * 注文ステータス更新
     * @description 注文ステータスを更新
     */
    put: operations["updateOrderStatus"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    OrderItem: {
      product_id?: string;
      product_name?: string;
      /** Format: double */
      price?: number;
      quantity?: number;
      /** Format: double */
      subtotal?: number;
    };
    Order: {
      id?: string;
      user_id?: string;
      items?: components["schemas"]["OrderItem"][];
      /** Format: double */
      subtotal?: number;
      /** Format: double */
      shipping_cost?: number;
      /** Format: double */
      tax?: number;
      /** Format: double */
      discount_amount?: number;
      /** Format: double */
      total?: number;
      /** @enum {string} */
      status?: "pending" | "processing" | "completed" | "cancelled";
      payment_method?: string;
      shipping_address?: string;
      points_used?: number;
      points_earned?: number;
      coupon_code?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    CreateOrderRequest: {
      items: components["schemas"]["OrderItem"][];
      payment_method: string;
      shipping_address: string;
      /** @default 0 */
      points_to_use?: number;
      coupon_code?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * 注文履歴取得
   * @description ユーザーの注文履歴を取得
   */
  getUserOrders: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": {
            orders?: components["schemas"]["Order"][];
            total?: number;
            current_page?: number;
            page_size?: number;
          };
        };
      };
    };
  };
  /**
   * 注文作成
   * @description 新しい注文を作成
   */
  createOrder: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrderRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      201: {
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
      /** @description リクエスト不正 */
      400: {
        content: never;
      };
    };
  };
  /**
   * 注文取得
   * @description 注文IDから注文情報を取得
   */
  getOrder: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
      /** @description 注文が見つかりません */
      404: {
        content: never;
      };
    };
  };
  /**
   * 注文ステータス更新
   * @description 注文ステータスを更新
   */
  updateOrderStatus: {
    parameters: {
      query: {
        status: "pending" | "processing" | "completed" | "cancelled";
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
      /** @description リクエスト不正 */
      400: {
        content: never;
      };
    };
  };
}
