/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/points/balance": {
    /**
     * ポイント残高取得
     * @description ユーザーのポイント残高を取得
     */
    get: operations["getBalance"];
  };
  "/points/earn": {
    /**
     * ポイント付与
     * @description ユーザーにポイントを付与
     */
    post: operations["earnPoints"];
  };
  "/points/use": {
    /**
     * ポイント使用
     * @description ユーザーのポイントを使用
     */
    post: operations["usePoints"];
  };
  "/points/transactions": {
    /**
     * トランザクション履歴取得
     * @description ポイントトランザクション履歴を取得
     */
    get: operations["getTransactions"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    PointBalance: {
      user_id?: string;
      total_points?: number;
      available_points?: number;
      reserved_points?: number;
      expired_points?: number;
      /** Format: date-time */
      last_updated?: string;
    };
    PointTransaction: {
      id?: string;
      user_id?: string;
      /** @enum {string} */
      type?: "earn" | "use" | "expire" | "refund";
      points?: number;
      balance?: number;
      reason?: string;
      related_order_id?: string;
      /** Format: date-time */
      expires_at?: string | null;
      /** Format: date-time */
      created_at?: string;
    };
    EarnPointsRequest: {
      points: number;
      reason: string;
      related_order_id?: string;
      /** Format: date-time */
      expires_at?: string | null;
    };
    UsePointsRequest: {
      points: number;
      reason: string;
      related_order_id?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * ポイント残高取得
   * @description ユーザーのポイント残高を取得
   */
  getBalance: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["PointBalance"];
        };
      };
      /** @description サーバーエラー */
      500: {
        content: never;
      };
    };
  };
  /**
   * ポイント付与
   * @description ユーザーにポイントを付与
   */
  earnPoints: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EarnPointsRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["PointBalance"];
        };
      };
      /** @description リクエスト不正 */
      400: {
        content: never;
      };
    };
  };
  /**
   * ポイント使用
   * @description ユーザーのポイントを使用
   */
  usePoints: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UsePointsRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["PointBalance"];
        };
      };
      /** @description リクエスト不正 */
      400: {
        content: never;
      };
    };
  };
  /**
   * トランザクション履歴取得
   * @description ポイントトランザクション履歴を取得
   */
  getTransactions: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": {
            transactions?: components["schemas"]["PointTransaction"][];
            total?: number;
            current_page?: number;
            page_size?: number;
          };
        };
      };
    };
  };
}
