/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/products/{id}": {
    /**
     * 商品詳細取得
     * @description 商品IDから商品情報を取得
     */
    get: operations["getProduct"];
  };
  "/products/search": {
    /**
     * 商品検索
     * @description キーワード・カテゴリ・価格範囲で商品検索
     */
    get: operations["searchProducts"];
  };
  "/products/featured": {
    /**
     * おすすめ商品取得
     * @description ピックアップ商品一覧を取得
     */
    get: operations["getFeaturedProducts"];
  };
  "/products/category/{category}": {
    /**
     * カテゴリ別商品取得
     * @description カテゴリから商品一覧を取得
     */
    get: operations["getProductsByCategory"];
  };
  "/products/{product_id}/skus": {
    /**
     * 商品のSKU一覧取得
     * @description 商品IDから有効なSKU一覧を取得
     */
    get: operations["getSKUsByProduct"];
  };
  "/products/{product_id}/with-skus": {
    /**
     * 商品とSKUをまとめて取得
     * @description 商品情報とSKU一覧を一括取得
     */
    get: operations["getProductWithSKUs"];
  };
  "/skus/{id}": {
    /**
     * SKU詳細取得
     * @description SKU IDからSKU情報を取得
     */
    get: operations["getSKU"];
  };
  "/skus/code/{code}": {
    /**
     * SKUコード検索
     * @description SKUコードからSKU情報を取得
     */
    get: operations["getSKUByCode"];
  };
  "/skus/low-stock": {
    /**
     * 低在庫SKU一覧
     * @description 在庫が閾値以下のSKU一覧を取得
     */
    get: operations["getLowStockSKUs"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Product: {
      /** @description 商品ID */
      id: string;
      /** @description 商品名 */
      name: string;
      /** @description 説明 */
      description?: string;
      /**
       * Format: double
       * @description 価格
       */
      price: number;
      /** @description 在庫数 */
      stock?: number;
      /** @description カテゴリ */
      category?: string;
      /** @description 画像URL */
      images?: string[];
      /**
       * Format: double
       * @description 評価
       */
      rating?: number;
      /** @description レビュー数 */
      review_count?: number;
      /** @description セール中か */
      is_sale?: boolean;
      /**
       * Format: double
       * @description セール価格
       */
      sale_price?: number | null;
      /**
       * Format: date-time
       * @description 作成日時
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description 更新日時
       */
      updated_at?: string;
      /** @description アクティブ状態 */
      is_active?: boolean;
    };
    SearchResult: {
      products?: components["schemas"]["Product"][];
      /** @description 総件数 */
      total?: number;
      /** @description 現在ページ */
      current_page?: number;
      /** @description 総ページ数 */
      total_pages?: number;
      /** @description ページサイズ */
      page_size?: number;
    };
    SKU: {
      /** @description SKU ID */
      id: string;
      /** @description 商品ID */
      product_id: string;
      /** @description SKUコード */
      sku_code: string;
      /** @description SKU名 */
      name: string;
      /**
       * @description バリエーション属性（色、サイズなど）
       * @example {
       *   "color": "Red",
       *   "size": "M"
       * }
       */
      attributes?: {
        [key: string]: string;
      };
      /**
       * Format: double
       * @description SKU価格
       */
      price: number;
      /** @description 在庫数 */
      stock: number;
      /** @description アクティブ状態 */
      is_active?: boolean;
      /**
       * Format: date-time
       * @description 作成日時
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description 更新日時
       */
      updated_at?: string;
    };
    ProductWithSKUs: {
      /** @description 商品ID */
      id: string;
      /** @description 商品名 */
      name: string;
      /** @description 説明 */
      description?: string;
      /**
       * Format: double
       * @description 基本価格
       */
      price: number;
      /** @description カテゴリ */
      category?: string;
      /** @description 画像URL */
      images?: string[];
      /**
       * Format: double
       * @description 評価
       */
      rating?: number;
      /** @description レビュー数 */
      review_count?: number;
      /** @description セール中か */
      is_sale?: boolean;
      /**
       * Format: double
       * @description セール価格
       */
      sale_price?: number | null;
      /**
       * Format: date-time
       * @description 作成日時
       */
      created_at?: string;
      /**
       * Format: date-time
       * @description 更新日時
       */
      updated_at?: string;
      /** @description アクティブ状態 */
      is_active?: boolean;
      /** @description SKU一覧 */
      skus: components["schemas"]["SKU"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * 商品詳細取得
   * @description 商品IDから商品情報を取得
   */
  getProduct: {
    parameters: {
      path: {
        /** @description Product ID */
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
      /** @description 商品が見つかりません */
      404: {
        content: never;
      };
      /** @description サーバーエラー */
      500: {
        content: never;
      };
    };
  };
  /**
   * 商品検索
   * @description キーワード・カテゴリ・価格範囲で商品検索
   */
  searchProducts: {
    parameters: {
      query?: {
        /** @description 検索キーワード */
        keyword?: string;
        /** @description カテゴリ */
        category?: string;
        /** @description 最低価格 */
        price_min?: number;
        /** @description 最高価格 */
        price_max?: number;
        /** @description ソート対象 */
        sort_by?: "price" | "rating" | "created_at";
        /** @description ソート順序 */
        sort_order?: "asc" | "desc";
        /** @description ページ番号 */
        page?: number;
        /** @description ページサイズ */
        page_size?: number;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["SearchResult"];
        };
      };
      /** @description リクエスト不正 */
      400: {
        content: never;
      };
      /** @description サーバーエラー */
      500: {
        content: never;
      };
    };
  };
  /**
   * おすすめ商品取得
   * @description ピックアップ商品一覧を取得
   */
  getFeaturedProducts: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Product"][];
        };
      };
      /** @description サーバーエラー */
      500: {
        content: never;
      };
    };
  };
  /**
   * カテゴリ別商品取得
   * @description カテゴリから商品一覧を取得
   */
  getProductsByCategory: {
    parameters: {
      query?: {
        /** @description ページ番号 */
        page?: number;
        /** @description ページサイズ */
        page_size?: number;
      };
      path: {
        /** @description カテゴリ名 */
        category: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["SearchResult"];
        };
      };
      /** @description リクエスト不正 */
      400: {
        content: never;
      };
      /** @description サーバーエラー */
      500: {
        content: never;
      };
    };
  };
  /**
   * 商品のSKU一覧取得
   * @description 商品IDから有効なSKU一覧を取得
   */
  getSKUsByProduct: {
    parameters: {
      path: {
        /** @description 商品ID */
        product_id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["SKU"][];
        };
      };
      /** @description 商品が見つかりません */
      404: {
        content: never;
      };
      /** @description サーバーエラー */
      500: {
        content: never;
      };
    };
  };
  /**
   * 商品とSKUをまとめて取得
   * @description 商品情報とSKU一覧を一括取得
   */
  getProductWithSKUs: {
    parameters: {
      path: {
        /** @description 商品ID */
        product_id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["ProductWithSKUs"];
        };
      };
      /** @description 商品が見つかりません */
      404: {
        content: never;
      };
      /** @description サーバーエラー */
      500: {
        content: never;
      };
    };
  };
  /**
   * SKU詳細取得
   * @description SKU IDからSKU情報を取得
   */
  getSKU: {
    parameters: {
      path: {
        /** @description SKU ID */
        id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["SKU"];
        };
      };
      /** @description SKUが見つかりません */
      404: {
        content: never;
      };
      /** @description サーバーエラー */
      500: {
        content: never;
      };
    };
  };
  /**
   * SKUコード検索
   * @description SKUコードからSKU情報を取得
   */
  getSKUByCode: {
    parameters: {
      path: {
        /** @description SKUコード */
        code: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["SKU"];
        };
      };
      /** @description SKUが見つかりません */
      404: {
        content: never;
      };
      /** @description サーバーエラー */
      500: {
        content: never;
      };
    };
  };
  /**
   * 低在庫SKU一覧
   * @description 在庫が閾値以下のSKU一覧を取得
   */
  getLowStockSKUs: {
    parameters: {
      query?: {
        /** @description 在庫閾値 */
        threshold?: number;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["SKU"][];
        };
      };
      /** @description サーバーエラー */
      500: {
        content: never;
      };
    };
  };
}
