/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/promotions/validate-coupon": {
    /**
     * クーポン検証
     * @description クーポンコードを検証して割引額を計算
     */
    post: operations["validateCoupon"];
  };
  "/promotions/coupons": {
    /**
     * アクティブなクーポン取得
     * @description 現在有効なクーポン一覧を取得
     */
    get: operations["getActiveCoupons"];
  };
  "/promotions/sales": {
    /**
     * アクティブなセール取得
     * @description 現在実施中のセール一覧を取得
     */
    get: operations["getActiveSales"];
  };
  "/promotions/sales/category/{category}": {
    /**
     * カテゴリ別セール取得
     * @description 指定カテゴリの適用セールを取得
     */
    get: operations["getSalesByCategory"];
  };
  "/promotions/sales/product/{product_id}": {
    /**
     * 商品別セール取得
     * @description 指定商品の適用セールを取得
     */
    get: operations["getSalesByProduct"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Coupon: {
      id?: string;
      code?: string;
      /** @enum {string} */
      status?: "active" | "expired" | "used" | "suspended";
      /** @enum {string} */
      discount_type?: "percentage" | "fixed_amount";
      /** Format: double */
      discount_value?: number;
      /** Format: double */
      max_discount?: number;
      /** Format: double */
      min_order_amount?: number;
      /** Format: date-time */
      start_date?: string;
      /** Format: date-time */
      end_date?: string;
      max_usage_count?: number;
      current_usage_count?: number;
      max_per_user?: number;
      applicable_categories?: string[];
      description?: string;
      /** Format: date-time */
      created_at?: string;
    };
    Sale: {
      id?: string;
      name?: string;
      description?: string;
      /** Format: date-time */
      start_date?: string;
      /** Format: date-time */
      end_date?: string;
      /** @enum {string} */
      discount_type?: "percentage" | "fixed_amount";
      /** Format: double */
      discount_value?: number;
      /** Format: double */
      max_discount?: number;
      applicable_categories?: string[];
      applicable_products?: string[];
      /** Format: date-time */
      created_at?: string;
    };
    ValidateCouponRequest: {
      code: string;
      /** Format: double */
      order_total: number;
      user_id: string;
      items?: {
          product_id?: string;
          category?: string;
        }[];
    };
    CouponValidationResult: {
      valid?: boolean;
      /** Format: double */
      discount_amount?: number;
      message?: string;
      coupon?: components["schemas"]["Coupon"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * クーポン検証
   * @description クーポンコードを検証して割引額を計算
   */
  validateCoupon: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidateCouponRequest"];
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["CouponValidationResult"];
        };
      };
      /** @description リクエスト不正 */
      400: {
        content: never;
      };
    };
  };
  /**
   * アクティブなクーポン取得
   * @description 現在有効なクーポン一覧を取得
   */
  getActiveCoupons: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Coupon"][];
        };
      };
    };
  };
  /**
   * アクティブなセール取得
   * @description 現在実施中のセール一覧を取得
   */
  getActiveSales: {
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Sale"][];
        };
      };
    };
  };
  /**
   * カテゴリ別セール取得
   * @description 指定カテゴリの適用セールを取得
   */
  getSalesByCategory: {
    parameters: {
      path: {
        category: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Sale"][];
        };
      };
    };
  };
  /**
   * 商品別セール取得
   * @description 指定商品の適用セールを取得
   */
  getSalesByProduct: {
    parameters: {
      path: {
        product_id: string;
      };
    };
    responses: {
      /** @description 成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Sale"][];
        };
      };
    };
  };
}
